### ISSUE TITLE
Couldnt get all tests to pass

### ISSUE THREAD

**Issue by mxdavis** [learn-co-curriculum/js-tictactoe-rails-api#27]
We couldn't get all tests to pass but all required functionality worked fine. We crossed out about 6 to 7 tests upon submit as per the advice of a learn expert.

**Comment by gj** [comment]
Hi @mxdavis (and @jwolfe890) !

The specs are working fine — I cloned down your solution, and your app is not exhibiting all of the required functionality. Here's a screenshot of a game state I was able to create with your project by alternately saving and retrieving the first saved game in the database:

<img width="380" alt="screen shot 2017-07-10 at 10 51 22" src="https://user-images.githubusercontent.com/17556281/28024158-e53955a8-655d-11e7-90c9-261bc5caf5a2.png">

Per your Ask a Question thread, it's almost never a good idea to comment out spec tests in order to pass a lab.

On another note, when we updated the lab the new solution branch did not propagate over to the `learn-co-students` repo, which is why so many tests were failing when you tried to copy over the solution branch's code. It's updated now, so thanks for pointing that out!
